In [1]:
# Import statements
# %run startup.py
import numpy as np

from package.simulation.simulation import Simulation
from package.simulation.graph import Graph
from package.circuit.circuit import Circuit


from dotenv import dotenv_values

SECRETS = dotenv_values("../envs/graphs.env")

TRAIN_DATA_PATH = SECRETS['TRAIN_DATA_PATH']
TEST_DATA_PATH = SECRETS['TEST_DATA_PATH']
PULL_UP_STRENGTH, PULL_DOWN_STRENGTH = list(map(int, SECRETS['BETA'].split(':')))
BETA = PULL_UP_STRENGTH / PULL_DOWN_STRENGTH
NUM_SAMPLES = int(SECRETS['NUM_SAMPLES'])
MAX_LENGTH = int(SECRETS['MAX_LENGTH'])

In [2]:
import os
os.listdir()

['3nand_generator.ipynb',
 '3nand_visualizer.ipynb',
 'app.py',
 'data_generator.ipynb',
 'graphmaker.ipynb',
 'graph_generator.ipynb',
 'package',
 'startup.py',
 'visualize.ipynb']

In [3]:
gates = ["2NAND", "1NOT", "2NOR"]
"""
What I want to do?
I want to make many circuits into one simulation object such that in each circuit, it is a single chain of gates.
The chain starts with appropriate number of drivers and the chain ends with one EOS node.
For that I will first make a graph object which will first make a chain of random number of gate ssized randomly.
"""

'\nWhat I want to do?\nI want to make many circuits into one simulation object such that in each circuit, it is a single chain of gates.\nThe chain starts with appropriate number of drivers and the chain ends with one EOS node.\nFor that I will first make a graph object which will first make a chain of random number of gate ssized randomly.\n'

In [4]:

# class Graph:
#     GATE_CHOICES = ["2NAND", "1NOT", "2NOR"]
#     INVERTING_GATES = ["1NOT", "2NAND", "2NOR"]
#     NON_INVERTING_GATES = ["2AND", "2OR"]
#     def __init__(self, name, max_num_of_gates = 20, max_sizing = 50):
#         self.name = name
#         self.max_num_of_gates = np.random.randint(10, max_num_of_gates)
#         self.max_sizing = max_sizing
#         self.circuit = self.__make_circuit()

#     def __make_circuit(self):
#         self.gate_list = list(np.random.choice(self.GATE_CHOICES, self.max_num_of_gates))
#         self.gate_sizes = np.random.randint(1, self.max_sizing, self.max_num_of_gates)
#         self.drivers = [f"v{i+1}" for i in range(int(self.gate_list[0][0]))]
#         self.driver_sizes = np.random.randint(1, self.max_sizing, len(self.drivers))

#         gate_dict, driver_dict, eos_dict = {}, {}, {}
#         for i in range(len(self.gate_list)):
#             gate_dict[f"gate{i+1}"] = {"type":self.gate_list[i], "k":int(self.gate_sizes[i]), "input_components" : [f"gate{i}" for _ in range(int(self.gate_list[i][0]))] if i > 0 else self.drivers}
#         for i in range(len(self.drivers)):
#             driver_dict[f"v{i+1}"] = {"ideal":False, "k":int(self.driver_sizes[i])}
#         eos_dict["k"] = np.random.randint(1, self.max_sizing)
#         eos_dict["input_gate"] = f"gate{len(self.gate_list)}"
#         eos_dict["capacitance"] = 10
#         # count number of invering gates in gate list
#         self.num_inverting_gates = len([gate for gate in self.gate_list if gate in self.INVERTING_GATES])
#         inverting = True if self.num_inverting_gates % 2  else False
        
#         self.circuit = Circuit(self.name, gate_dict, driver_dict, eos_dict, inverting)
#         return self.circuit

#     def __repr__(self):
#         return f"{self.name}: {self.circuit}"


In [5]:
graphs = [Graph(f"circuit{i}", MAX_LENGTH, 50, BETA=BETA) for i in range(1, 1000+1)]
simulation = Simulation("datasetgenerator", [graph.circuit for graph in graphs])
simulation.save(TEST_DATA_PATH+f"/{simulation.name}.sp")

[10.  4.  6.  3.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[11.  5.  4.  2.  1.  2.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[14.  7.  4.  6.  2.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[9. 5. 4. 5. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[7. 6. 3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[14.  5.  4.  6.  2.  2.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.]
[4. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4. 4. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[11.  4.  2.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[6. 4. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 8. 4. 3. 1. 2. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[

In [6]:
graphs[0].idealized_circuit

/////////////////////3 STAGE NAND/////////////////////////////
.inc "/home/lalithsai20/EMDproject/7nm_TT_160803.pm"

V1CIRCUIT1 v1circuit1 0 pwl(0 0.7 0.9999us 0.7 1us 0 2us 0)
Mv1circuit1driverm0 out_v1circuit1driver v1circuit1 vdd vdd pmos_lvt nfin = 30
Mv1circuit1driverm1 out_v1circuit1driver v1circuit1 0 0 nmos_lvt nfin = 20

V2CIRCUIT1 v2circuit1 0 pwl(0 0.7 0.9999us 0.7 1us 0 2us 0)
Mv2circuit1driverm0 out_v2circuit1driver v2circuit1 vdd vdd pmos_lvt nfin = 24
Mv2circuit1driverm1 out_v2circuit1driver v2circuit1 0 0 nmos_lvt nfin = 16

Mgate1circuit1m0 out_gate1circuit1 out_v1circuit1driver vdd vdd pmos_lvt nfin = 6
Mgate1circuit1m1 out_gate1circuit1 out_v2circuit1driver vdd vdd pmos_lvt nfin = 6
Mgate1circuit1m2 out_gate1circuit1 out_v1circuit1driver gate1circuit1mid 0 nmos_lvt nfin = 8
Mgate1circuit1m3 gate1circuit1mid out_v2circuit1driver 0 0 nmos_lvt nfin = 8

Mgate2circuit1m0 out_gate2circuit1intermediate out_gate1circuit1 gate2circuit1mid vdd pmos_lvt nfin = 6
Mgate2circuit1

In [11]:
graphs[0].circuit

/////////////////////3 STAGE NAND/////////////////////////////
.inc "/home/lalithsai20/EMDproject/7nm_TT_160803.pm"

V1CIRCUIT1 v1circuit1 0 pwl(0 0.7 0.9999us 0.7 1us 0 2us 0)
Mv1circuit1driverm0 out_v1circuit1driver v1circuit1 vdd vdd pmos_lvt nfin = 84
Mv1circuit1driverm1 out_v1circuit1driver v1circuit1 0 0 nmos_lvt nfin = 56

V2CIRCUIT1 v2circuit1 0 pwl(0 0.7 0.9999us 0.7 1us 0 2us 0)
Mv2circuit1driverm0 out_v2circuit1driver v2circuit1 vdd vdd pmos_lvt nfin = 105
Mv2circuit1driverm1 out_v2circuit1driver v2circuit1 0 0 nmos_lvt nfin = 70

Mgate1circuit1m0 out_gate1circuit1intermediate out_v1circuit1driver gate1circuit1mid vdd pmos_lvt nfin = 156
Mgate1circuit1m1 gate1circuit1mid out_v2circuit1driver vdd vdd pmos_lvt nfin = 156
Mgate1circuit1m2 out_gate1circuit1intermediate out_v1circuit1driver 0 0 nmos_lvt nfin = 52
Mgate1circuit1m3 out_gate1circuit1intermediate out_v2circuit1driver 0 0 nmos_lvt nfin = 52
Mgate1circuit1m4 out_gate1circuit1 out_gate1circuit1intermediate 0 0 nmos_lvt 

In [6]:
# for graph in graphs:
#     graph.save_graph_matrices(TRAIN_DATA_PATH+f"/train_data/{graph.name}.npz")

# graphs[0].save_graph_matrices(TRAIN_DATA_PATH+f"/train_data/{graphs[0].name}.npz")

In [7]:
for graph in graphs:
    graph.save_adjacency_list_and_feature_matrix(TRAIN_DATA_PATH+f"/train_data/{graph.name}.npz")

In [8]:
g = Graph("circuit1", 25, 50)
g.make_graph_matrices()

(array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [-1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0., -1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0., -1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0., -1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0., -1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  1.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  1.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  1., 

In [9]:
g.make_adjacency_list_and_feature_matrix()

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]]),
 array([[ 0.,  2., 11., 42., 11.],
        [ 1.,  1., 11., 42., 47.],
        [ 2.,  0., 11., 42., 19.],
        [ 3.,  4., 11., 42., 49.],
        [ 4.,  1., 11., 42., 28.],
        [ 5.,  2., 11., 42., 34.],
        [ 6.,  1., 11., 42., 42.],
        [ 7.,  2., 11., 42., 25.],
        [ 8.,  2., 11., 42., 22.],
        [ 9.,  4., 11., 42., 20.],
        [10.,  1., 11., 42., 47.],
        [11.,  0., 11., 42., 28.],
        [12.,  1., 11., 42., 47.],
        [13.,  3., 11., 42.,  3.],
        [14.,  2., 11., 42.,  9.],
        [15.,  4., 11., 42., 11.],
        [16.,  1., 11., 42., 32.]]))

In [10]:
train_data = [ (np.load(TRAIN_DATA_PATH + f"/train_data/circuit{i}.npz")['adj_list'],  np.load(TRAIN_DATA_PATH + f"/train_data/circuit{i}.npz")['feature_matrix']) for i in range(1, 1000+1) ]

In [11]:
i = 10
train_data[i][0].shape, train_data[i][1].shape

((2, 17), (18, 5))

In [12]:
train_data[i][0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17]])